#!/usr/bin/env python3
import PyPDF2
import re
import os

def extract_pdf_text(pdf_path):
    """Extract all text from PDF"""
    try:
        with open(pdf_path, 'rb') as file:
            reader = PyPDF2.PdfReader(file)
            all_text = ""
            
            for i, page in enumerate(reader.pages):
                if i % 100 == 0:
                    print(f"Processing page {i+1}...")
                text = page.extract_text()
                all_text += text + "\n"
            
            return all_text
    except Exception as e:
        print(f"Error reading PDF: {e}")
        return None

def extract_book_by_lines(lines, start_line, end_line, book_name):
    """Extract book text between specific line numbers"""
    book_lines = []
    
    for i in range(start_line, min(end_line, len(lines))):
        line = lines[i].strip()
        if line:
            book_lines.append(line)
    
    return '\n'.join(book_lines)

def extract_book_by_pattern(text, start_patterns, book_name):
    """Extract book text by finding start patterns"""
    lines = text.split('\n')
    
    for start_pattern in start_patterns:
        for i, line in enumerate(lines):
            if re.search(start_pattern, line, re.IGNORECASE):
                print(f"Found {book_name} starting at line {i}: {line.strip()}")
                
                # Extract text from this point
                book_lines = []
                j = i + 1
                
                # End patterns to stop extraction
                end_patterns = [
                    r'^(Genesis|Exodus|Leviticus|Numbers|Deuteronomy)',
                    r'^(Matthew|Mark|Luke|John|Acts|Romans)',
                    r'^(Tobit|Judith|Wisdom|Sirach|Baruch|Maccabees)',
                    r'^(THE\s+HISTORY\s+OF\s+SUSANNA)',
                    r'^(BEL\s+AND\s+THE\s+DRAGON)',
                    r'^\s*THE\s+NEW\s+TESTAMENT',
                    r'^\s*Appendix'
                ]
                
                while j < len(lines) and len(book_lines) < 3000:
                    line = lines[j].strip()
                    
                    # Check if we've reached another book
                    is_end = False
                    for end_pattern in end_patterns:
                        if re.match(end_pattern, line, re.IGNORECASE) and book_name.lower() not in line.lower():
                            is_end = True
                            break
                    
                    if is_end:
                        print(f"Stopping extraction at line {j}: {line}")
                        break
                    
                    if line:
                        book_lines.append(line)
                    
                    j += 1
                
                if book_lines:
                    return '\n'.join(book_lines)
    
    return None

def fix_text_spacing(text):
    """Fix spacing issues in the extracted text"""
    if not text:
        return None
    
    # Apply more comprehensive spacing fixes
    # Add spaces before capital letters that follow lowercase letters
    text = re.sub(r'([a-z])([A-Z])', r'\1 \2', text)
    
    # Add spaces before numbers that follow letters
    text = re.sub(r'([a-z])(\d)', r'\1 \2', text)
    
    # Add spaces after numbers that precede letters
    text = re.sub(r'(\d)([a-z])', r'\1 \2', text)
    
    # Fix common word concatenations
    common_fixes = [
        (r'\bofthe\b', 'of the'),
        (r'\binthe\b', 'in the'),
        (r'\btothe\b', 'to the'),
        (r'\bfrom the\b', 'from the'),
        (r'\bandthe\b', 'and the'),
        (r'\bwiththe\b', 'with the'),
        (r'\boutof\b', 'out of'),
        (r'\binto\b', 'in to'),
        (r'\bmylife\b', 'my life'),
        (r'\bmykindred\b', 'my kindred'),
        (r'\bmynation\b', 'my nation'),
        (r'\bmyown\b', 'my own'),
        (r'\ballthe\b', 'all the'),
        (r'\ballmy\b', 'all my'),
        (r'\btheway\b', 'the way'),
        (r'\btheways\b', 'the ways'),
        (r'\bthedays\b', 'the days'),
        (r'\btheland\b', 'the land'),
        (r'\bthehouse\b', 'the house'),
        (r'\bthetime\b', 'the time'),
        (r'\bwhen I\b', 'when I'),
        (r'\bthat I\b', 'that I'),
        (r'\bif I\b', 'if I'),
        (r'\bas I\b', 'as I'),
        (r'\bbecause I\b', 'because I'),
        (r'\buntil I\b', 'until I'),
        (r'\bwhile I\b', 'while I'),
        (r'\bsince I\b', 'since I'),
        (r'\bafter I\b', 'after I'),
        (r'\bbefore I\b', 'before I'),
        (r'\bwhen he\b', 'when he'),
        (r'\bthat he\b', 'that he'),
        (r'\bif he\b', 'if he'),
        (r'\bas he\b', 'as he'),
        (r'\bbecause he\b', 'because he'),
        (r'\buntil he\b', 'until he'),
        (r'\bwhile he\b', 'while he'),
        (r'\bsince he\b', 'since he'),
        (r'\bafter he\b', 'after he'),
        (r'\bbefore he\b', 'before he'),
        (r'\bwhen they\b', 'when they'),
        (r'\bthat they\b', 'that they'),
        (r'\bif they\b', 'if they'),
        (r'\bas they\b', 'as they'),
        (r'\bbecause they\b', 'because they'),
        (r'\buntil they\b', 'until they'),
        (r'\bwhile they\b', 'while they'),
        (r'\bsince they\b', 'since they'),
        (r'\bafter they\b', 'after they'),
        (r'\bbefore they\b', 'before they'),
        (r'\bwhen we\b', 'when we'),
        (r'\bthat we\b', 'that we'),
        (r'\bif we\b', 'if we'),
        (r'\bas we\b', 'as we'),
        (r'\bbecause we\b', 'because we'),
        (r'\buntil we\b', 'until we'),
        (r'\bwhile we\b', 'while we'),
        (r'\bsince we\b', 'since we'),
        (r'\bafter we\b', 'after we'),
        (r'\bbefore we\b', 'before we'),
        (r'\bwhen you\b', 'when you'),
        (r'\bthat you\b', 'that you'),
        (r'\bif you\b', 'if you'),
        (r'\bas you\b', 'as you'),
        (r'\bbecause you\b', 'because you'),
        (r'\buntil you\b', 'until you'),
        (r'\bwhile you\b', 'while you'),
        (r'\bsince you\b', 'since you'),
        (r'\bafter you\b', 'after you'),
        (r'\bbefore you\b', 'before you'),
        (r'\btome\b', 'to me'),
        (r'\bfrom me\b', 'from me'),
        (r'\bwith me\b', 'with me'),
        (r'\bfor me\b', 'for me'),
        (r'\bby me\b', 'by me'),
        (r'\bthrough me\b', 'through me'),
        (r'\babout me\b', 'about me'),
        (r'\bagainst me\b', 'against me'),
        (r'\bbesides me\b', 'besides me'),
        (r'\bbeyond me\b', 'beyond me'),
        (r'\bwithout me\b', 'without me'),
        (r'\bduring me\b', 'during me'),
        (r'\bupon me\b', 'upon me'),
        (r'\bover me\b', 'over me'),
        (r'\bunder me\b', 'under me'),
        (r'\bbehind me\b', 'behind me'),
        (r'\bbefore me\b', 'before me'),
        (r'\binfront of me\b', 'in front of me'),
        (r'\bin front ofme\b', 'in front of me'),
        (r'\bwithin me\b', 'within me'),
        (r'\bmeinto\b', 'me into'),
        (r'\bhiminto\b', 'him into'),
        (r'\bherinto\b', 'her into'),
        (r'\btheminto\b', 'them into'),
        (r'\businto\b', 'us into'),
        (r'\byouinto\b', 'you into'),
        (r'\bitinto\b', 'it into'),
        (r'\bthatit\b', 'that it'),
        (r'\bwhichit\b', 'which it'),
        (r'\bwhereit\b', 'where it'),
        (r'\bwhen it\b', 'when it'),
        (r'\bhow it\b', 'how it'),
        (r'\bwhy it\b', 'why it'),
        (r'\bwhat it\b', 'what it'),
        (r'\bwho it\b', 'who it'),
        (r'\bwhose it\b', 'whose it'),
        (r'\bwhom it\b', 'whom it'),
        (r'\bIwas\b', 'I was'),
        (r'\bIam\b', 'I am'),
        (r'\bIdid\b', 'I did'),
        (r'\bIdo\b', 'I do'),
        (r'\bIwill\b', 'I will'),
        (r'\bIshall\b', 'I shall'),
        (r'\bIhave\b', 'I have'),
        (r'\bIhad\b', 'I had'),
        (r'\bIcan\b', 'I can'),
        (r'\bIcould\b', 'I could'),
        (r'\bImay\b', 'I may'),
        (r'\bImight\b', 'I might'),
        (r'\bImust\b', 'I must'),
        (r'\bIshould\b', 'I should'),
        (r'\bIwould\b', 'I would'),
        (r'\bIought\b', 'I ought'),
        (r'\bIused\b', 'I used'),
        (r'\bIwent\b', 'I went'),
        (r'\bIcame\b', 'I came'),
        (r'\bIsaw\b', 'I saw'),
        (r'\bIsaid\b', 'I said'),
        (r'\bItold\b', 'I told'),
        (r'\bIheard\b', 'I heard'),
        (r'\bIfound\b', 'I found'),
        (r'\bItook\b', 'I took'),
        (r'\bIgave\b', 'I gave'),
        (r'\bIgot\b', 'I got'),
        (r'\bImade\b', 'I made'),
        (r'\bIthought\b', 'I thought'),
        (r'\bIknow\b', 'I know'),
        (r'\bIknew\b', 'I knew'),
        (r'\bIfeel\b', 'I feel'),
        (r'\bIfelt\b', 'I felt'),
        (r'\bIlook\b', 'I look'),
        (r'\bIlooked\b', 'I looked'),
        (r'\bIsee\b', 'I see'),
        (r'\bIask\b', 'I ask'),
        (r'\bIasked\b', 'I asked'),
        (r'\bIanswer\b', 'I answer'),
        (r'\bIanswered\b', 'I answered'),
        (r'\bIbelieve\b', 'I believe'),
        (r'\bIbelieved\b', 'I believed'),
        (r'\bIhope\b', 'I hope'),
        (r'\bIhoped\b', 'I hoped'),
        (r'\bIwish\b', 'I wish'),
        (r'\bIwished\b', 'I wished'),
        (r'\bIwant\b', 'I want'),
        (r'\bIwanted\b', 'I wanted'),
        (r'\bIneed\b', 'I need'),
        (r'\bIneeded\b', 'I needed'),
        (r'\bIlike\b', 'I like'),
        (r'\bIliked\b', 'I liked'),
        (r'\bIlove\b', 'I love'),
        (r'\bIloved\b', 'I loved'),
        (r'\bIhate\b', 'I hate'),
        (r'\bIhated\b', 'I hated'),
        (r'\bIfear\b', 'I fear'),
        (r'\bIfeared\b', 'I feared'),
        (r'\bIworry\b', 'I worry'),
        (r'\bIworried\b', 'I worried'),
        (r'\bIcare\b', 'I care'),
        (r'\bIcared\b', 'I cared'),
        (r'\bIhelp\b', 'I help'),
        (r'\bIhelped\b', 'I helped'),
        (r'\bIwork\b', 'I work'),
        (r'\bIworked\b', 'I worked'),
        (r'\bIlive\b', 'I live'),
        (r'\bIlived\b', 'I lived'),
        (r'\bIdie\b', 'I die'),
        (r'\bIdied\b', 'I died'),
        (r'\bIeat\b', 'I eat'),
        (r'\bIate\b', 'I ate'),
        (r'\bIdrink\b', 'I drink'),
        (r'\bIdrank\b', 'I drank'),
        (r'\bIsleep\b', 'I sleep'),
        (r'\bIslept\b', 'I slept'),
        (r'\bIwake\b', 'I wake'),
        (r'\bIwoke\b', 'I woke'),
        (r'\bIstand\b', 'I stand'),
        (r'\bIstood\b', 'I stood'),
        (r'\bIsit\b', 'I sit'),
        (r'\bIsat\b', 'I sat'),
        (r'\bIlie\b', 'I lie'),
        (r'\bIlay\b', 'I lay'),
        (r'\bIwalk\b', 'I walk'),
        (r'\bIwalked\b', 'I walked'),
        (r'\bIrun\b', 'I run'),
        (r'\bIran\b', 'I ran'),
        (r'\bIjump\b', 'I jump'),
        (r'\bIjumped\b', 'I jumped'),
        (r'\bIfall\b', 'I fall'),
        (r'\bIfell\b', 'I fell'),
        (r'\bIrise\b', 'I rise'),
        (r'\bIrose\b', 'I rose'),
        (r'\bIfly\b', 'I fly'),
        (r'\bIflew\b', 'I flew'),
        (r'\bIswim\b', 'I swim'),
        (r'\bIswam\b', 'I swam'),
        (r'\bIdrive\b', 'I drive'),
        (r'\bIdrove\b', 'I drove'),
        (r'\bIride\b', 'I ride'),
        (r'\bIrode\b', 'I rode'),
        (r'\bIsing\b', 'I sing'),
        (r'\bIsang\b', 'I sang'),
        (r'\bIdance\b', 'I dance'),
        (r'\bIdanced\b', 'I danced'),
        (r'\bIplay\b', 'I play'),
        (r'\bIplayed\b', 'I played'),
        (r'\bIread\b', 'I read'),
        (r'\bIwrite\b', 'I write'),
        (r'\bIwrote\b', 'I wrote'),
        (r'\bIdraw\b', 'I draw'),
        (r'\bIdrew\b', 'I drew'),
        (r'\bIpaint\b', 'I paint'),
        (r'\bIpainted\b', 'I painted'),
        (r'\bIbuild\b', 'I build'),
        (r'\bIbuilt\b', 'I built'),
        (r'\bIbreak\b', 'I break'),
        (r'\bIbroke\b', 'I broke'),
        (r'\bIfix\b', 'I fix'),
        (r'\bIfixed\b', 'I fixed'),
        (r'\bIclean\b', 'I clean'),
        (r'\bIcleaned\b', 'I cleaned'),
        (r'\bIwash\b', 'I wash'),
        (r'\bIwashed\b', 'I washed'),
        (r'\bIcook\b', 'I cook'),
        (r'\bIcooked\b', 'I cooked'),
        (r'\bIbake\b', 'I bake'),
        (r'\bIbaked\b', 'I baked'),
        (r'\bIshop\b', 'I shop'),
        (r'\bIshopped\b', 'I shopped'),
        (r'\bIbuy\b', 'I buy'),
        (r'\bIbought\b', 'I bought'),
        (r'\bIsell\b', 'I sell'),
        (r'\bIsold\b', 'I sold'),
        (r'\bIpay\b', 'I pay'),
        (r'\bIpaid\b', 'I paid'),
        (r'\bIowe\b', 'I owe'),
        (r'\bIowed\b', 'I owed'),
        (r'\bIlend\b', 'I lend'),
        (r'\bIlent\b', 'I lent'),
        (r'\bIborrow\b', 'I borrow'),
        (r'\bIborrowed\b', 'I borrowed'),
        (r'\bIsave\b', 'I save'),
        (r'\bIsaved\b', 'I saved'),
        (r'\bIspend\b', 'I spend'),
        (r'\bIspent\b', 'I spent'),
        (r'\bIearn\b', 'I earn'),
        (r'\bIearned\b', 'I earned'),
        (r'\bIwin\b', 'I win'),
        (r'\bIwon\b', 'I won'),
        (r'\bIlose\b', 'I lose'),
        (r'\bIlost\b', 'I lost'),
        (r'\bIgain\b', 'I gain'),
        (r'\bIgained\b', 'I gained'),
        (r'\bIfind\b', 'I find'),
        (r'\bIlook for\b', 'I look for'),
        (r'\bIsearch\b', 'I search'),
        (r'\bIsearched\b', 'I searched'),
        (r'\bIhide\b', 'I hide'),
        (r'\bIhid\b', 'I hid'),
        (r'\bIshow\b', 'I show'),
        (r'\bIshowed\b', 'I showed'),
        (r'\bIteach\b', 'I teach'),
        (r'\bItaught\b', 'I taught'),
        (r'\bIlearn\b', 'I learn'),
        (r'\bIlearned\b', 'I learned'),
        (r'\bIstuddy\b', 'I study'),
        (r'\bIstudied\b', 'I studied'),
        (r'\bIpractice\b', 'I practice'),
        (r'\bIpracticed\b', 'I practiced'),
        (r'\bItrain\b', 'I train'),
        (r'\bItrained\b', 'I trained'),
        (r'\bIexercise\b', 'I exercise'),
        (r'\bIexercised\b', 'I exercised'),
        (r'\bItest\b', 'I test'),
        (r'\bItested\b', 'I tested'),
        (r'\bItry\b', 'I try'),
        (r'\bItried\b', 'I tried'),
        (r'\bIattempt\b', 'I attempt'),
        (r'\bIattempted\b', 'I attempted'),
        (r'\bIsucceed\b', 'I succeed'),
        (r'\bIsucceeded\b', 'I succeeded'),
        (r'\bIfail\b', 'I fail'),
        (r'\bIfailed\b', 'I failed'),
        (r'\bIstart\b', 'I start'),
        (r'\bIstarted\b', 'I started'),
        (r'\bIbegin\b', 'I begin'),
        (r'\bIbegan\b', 'I began'),
        (r'\bIcontinue\b', 'I continue'),
        (r'\bIcontinued\b', 'I continued'),
        (r'\bIstop\b', 'I stop'),
        (r'\bIstopped\b', 'I stopped'),
        (r'\bIend\b', 'I end'),
        (r'\bIended\b', 'I ended'),
        (r'\bIfinish\b', 'I finish'),
        (r'\bIfinished\b', 'I finished'),
        (r'\bIcomplete\b', 'I complete'),
        (r'\bIcompleted\b', 'I completed'),
        (r'\bIquit\b', 'I quit'),
        (r'\bIleave\b', 'I leave'),
        (r'\bIleft\b', 'I left'),
        (r'\bIreturn\b', 'I return'),
        (r'\bIreturned\b', 'I returned'),
        (r'\bIcome\b', 'I come'),
        (r'\bIarrive\b', 'I arrive'),
        (r'\barrived\b', 'I arrived'),
        (r'\bIdepart\b', 'I depart'),
        (r'\bIdeparted\b', 'I departed'),
        (r'\bItravel\b', 'I travel'),
        (r'\bItraveled\b', 'I traveled'),
        (r'\bIvisit\b', 'I visit'),
        (r'\bIvisited\b', 'I visited'),
        (r'\bIstay\b', 'I stay'),
        (r'\bIstayed\b', 'I stayed'),
        (r'\bIremain\b', 'I remain'),
        (r'\bIremained\b', 'I remained'),
        (r'\bIwait\b', 'I wait'),
        (r'\bIwaited\b', 'I waited'),
        (r'\bIhurry\b', 'I hurry'),
        (r'\bIhurried\b', 'I hurried'),
        (r'\bIrush\b', 'I rush'),
        (r'\bIrushed\b', 'I rushed'),
        (r'\bIslow\b', 'I slow'),
        (r'\bIslowed\b', 'I slowed'),
        (r'\bIpause\b', 'I pause'),
        (r'\bIpaused\b', 'I paused'),
        (r'\bIrest\b', 'I rest'),
        (r'\bIrested\b', 'I rested'),
        (r'\bIrelax\b', 'I relax'),
        (r'\bIrelaxed\b', 'I relaxed'),
        (r'\bIenjoy\b', 'I enjoy'),
        (r'\bIenjoyed\b', 'I enjoyed'),
        (r'\bIhave fun\b', 'I have fun'),
        (r'\bIhad fun\b', 'I had fun'),
        (r'\bIlaugh\b', 'I laugh'),
        (r'\bIlaughed\b', 'I laughed'),
        (r'\bIsmile\b', 'I smile'),
        (r'\bIsmiled\b', 'I smiled'),
        (r'\bIcry\b', 'I cry'),
        (r'\bIcried\b', 'I cried'),
        (r'\bIweep\b', 'I weep'),
        (r'\bIwept\b', 'I wept'),
        (r'\bIsob\b', 'I sob'),
        (r'\bIsobbed\b', 'I sobbed'),
        (r'\bIshout\b', 'I shout'),
        (r'\bIshouted\b', 'I shouted'),
        (r'\bIyell\b', 'I yell'),
        (r'\bIyelled\b', 'I yelled'),
        (r'\bIscream\b', 'I scream'),
        (r'\bIscreamed\b', 'I screamed'),
        (r'\bIwhisper\b', 'I whisper'),
        (r'\bIwhispered\b', 'I whispered'),
        (r'\bImumble\b', 'I mumble'),
        (r'\bImumbled\b', 'I mumbled'),
        (r'\bImutter\b', 'I mutter'),
        (r'\bImuttered\b', 'I muttered'),
        (r'\bIspeak\b', 'I speak'),
        (r'\bIspoke\b', 'I spoke'),
        (r'\bItalk\b', 'I talk'),
        (r'\bItalked\b', 'I talked'),
        (r'\bIchat\b', 'I chat'),
        (r'\bIchatted\b', 'I chatted'),
        (r'\bIdiscuss\b', 'I discuss'),
        (r'\bIdiscussed\b', 'I discussed'),
        (r'\bIdebate\b', 'I debate'),
        (r'\bIdebated\b', 'I debated'),
        (r'\bIargue\b', 'I argue'),
        (r'\bIargued\b', 'I argued'),
        (r'\bIfight\b', 'I fight'),
        (r'\bIfought\b', 'I fought'),
        (r'\bIquarrel\b', 'I quarrel'),
        (r'\bIquarreled\b', 'I quarreled'),
        (r'\bIdisagree\b', 'I disagree'),
        (r'\bIdisagreed\b', 'I disagreed'),
        (r'\bIagree\b', 'I agree'),
        (r'\bIagreed\b', 'I agreed'),
        (r'\bIaccept\b', 'I accept'),
        (r'\bIaccepted\b', 'I accepted'),
        (r'\bIreject\b', 'I reject'),
        (r'\bIrejected\b', 'I rejected'),
        (r'\bIrefuse\b', 'I refuse'),
        (r'\bIrefused\b', 'I refused'),
        (r'\bIdeny\b', 'I deny'),
        (r'\bIdenied\b', 'I denied'),
        (r'\bIadmit\b', 'I admit'),
        (r'\bIadmitted\b', 'I admitted'),
        (r'\bIconfess\b', 'I confess'),
        (r'\bIconfessed\b', 'I confessed'),
        (r'\bIapologize\b', 'I apologize'),
        (r'\bIapologized\b', 'I apologized'),
        (r'\bIforgive\b', 'I forgive'),
        (r'\bIforgave\b', 'I forgave'),
        (r'\bIforget\b', 'I forget'),
        (r'\bIforgot\b', 'I forgot'),
        (r'\bIremember\b', 'I remember'),
        (r'\bIremembered\b', 'I remembered'),
        (r'\bIrecall\b', 'I recall'),
        (r'\bIrecalled\b', 'I recalled'),
        (r'\bIrecognize\b', 'I recognize'),
        (r'\bIrecognized\b', 'I recognized'),
        (r'\bIrealise\b', 'I realise'),
        (r'\bIrealised\b', 'I realised'),
        (r'\bIrealize\b', 'I realize'),
        (r'\bIrealized\b', 'I realized'),
        (r'\bIunderstand\b', 'I understand'),
        (r'\bIunderstood\b', 'I understood'),
        (r'\bIcomprehend\b', 'I comprehend'),
        (r'\bIcomprehended\b', 'I comprehended'),
        (r'\bIgrasp\b', 'I grasp'),
        (r'\bIgrasped\b', 'I grasped'),
        (r'\bIperceive\b', 'I perceive'),
        (r'\bIperceived\b', 'I perceived'),
        (r'\bInotice\b', 'I notice'),
        (r'\bInoticed\b', 'I noticed'),
        (r'\bIobserve\b', 'I observe'),
        (r'\bIobserved\b', 'I observed'),
        (r'\bIwatch\b', 'I watch'),
        (r'\bIwatched\b', 'I watched'),
        (r'\bIstare\b', 'I stare'),
        (r'\bIstared\b', 'I stared'),
        (r'\bIglance\b', 'I glance'),
        (r'\bIglanced\b', 'I glanced'),
        (r'\bIpeek\b', 'I peek'),
        (r'\bIpeeked\b', 'I peeked'),
        (r'\bIglimpse\b', 'I glimpse'),
        (r'\bIglimpsed\b', 'I glimpsed'),
        (r'\bIspy\b', 'I spy'),
        (r'\bIspied\b', 'I spied'),
        (r'\bIlisten\b', 'I listen'),
        (r'\bIlistened\b', 'I listened'),
        (r'\bIeavesdrop\b', 'I eavesdrop'),
        (r'\bIeavesdropped\b', 'I eavesdropped'),
        (r'\bIoverhear\b', 'I overhear'),
        (r'\bIoverheard\b', 'I overheard'),
        (r'\bItaste\b', 'I taste'),
        (r'\bItasted\b', 'I tasted'),
        (r'\bIsmell\b', 'I smell'),
        (r'\bIsmelled\b', 'I smelled'),
        (r'\bItouch\b', 'I touch'),
        (r'\bItouched\b', 'I touched'),
        (r'\bIrub\b', 'I rub'),
        (r'\bIrubbed\b', 'I rubbed'),
        (r'\bIscratch\b', 'I scratch'),
        (r'\bIscratched\b', 'I scratched'),
        (r'\bIpoke\b', 'I poke'),
        (r'\bIpoked\b', 'I poked'),
        (r'\bIpush\b', 'I push'),
        (r'\bIpushed\b', 'I pushed'),
        (r'\bIpull\b', 'I pull'),
        (r'\bIpulled\b', 'I pulled'),
        (r'\bIlift\b', 'I lift'),
        (r'\bIlifted\b', 'I lifted'),
        (r'\bIcarry\b', 'I carry'),
        (r'\bIcarried\b', 'I carried'),
        (r'\bIhold\b', 'I hold'),
        (r'\bIheld\b', 'I held'),
        (r'\bIgrab\b', 'I grab'),
        (r'\bIgrabbed\b', 'I grabbed'),
        (r'\bIgrip\b', 'I grip'),
        (r'\bIgripped\b', 'I gripped'),
        (r'\bIgrasp\b', 'I grasp'),
        (r'\bIgrasped\b', 'I grasped'),
        (r'\bIclutch\b', 'I clutch'),
        (r'\bIclutched\b', 'I clutched'),
        (r'\bIsqueeze\b', 'I squeeze'),
        (r'\bIsqueezed\b', 'I squeezed'),
        (r'\bIpress\b', 'I press'),
        (r'\bIpressed\b', 'I pressed'),
        (r'\bIrelease\b', 'I release'),
        (r'\bIreleased\b', 'I released'),
        (r'\bIlet go\b', 'I let go'),
        (r'\bIdrop\b', 'I drop'),
        (r'\bIdropped\b', 'I dropped'),
        (r'\bIthrow\b', 'I throw'),
        (r'\bIthrew\b', 'I threw'),
        (r'\bIcatch\b', 'I catch'),
        (r'\bIcaught\b', 'I caught'),
        (r'\bIhit\b', 'I hit'),
        (r'\bIkick\b', 'I kick'),
        (r'\bIkicked\b', 'I kicked'),
        (r'\bIpunch\b', 'I punch'),
        (r'\bIpunched\b', 'I punched'),
        (r'\bIslap\b', 'I slap'),
        (r'\bIslapped\b', 'I slapped'),
        (r'\bIstrike\b', 'I strike'),
        (r'\bIstruck\b', 'I struck'),
        (r'\bIbeat\b', 'I beat'),
        (r'\bIknock\b', 'I knock'),
        (r'\bIknocked\b', 'I knocked'),
        (r'\bItap\b', 'I tap'),
        (r'\bItapped\b', 'I tapped'),
        (r'\bIopen\b', 'I open'),
        (r'\bIopened\b', 'I opened'),
        (r'\bIclose\b', 'I close'),
        (r'\bIclosed\b', 'I closed'),
        (r'\bIshut\b', 'I shut'),
        (r'\bIlock\b', 'I lock'),
        (r'\bIlocked\b', 'I locked'),
        (r'\bIunlock\b', 'I unlock'),
        (r'\bIunlocked\b', 'I unlocked'),
        (r'\bIturn\b', 'I turn'),
        (r'\bIturned\b', 'I turned'),
        (r'\bItwist\b', 'I twist'),
        (r'\bItwisted\b', 'I twisted'),
        (r'\bIbend\b', 'I bend'),
        (r'\bIbent\b', 'I bent'),
        (r'\bIfold\b', 'I fold'),
        (r'\bIfolded\b', 'I folded'),
        (r'\bIunfold\b', 'I unfold'),
        (r'\bIunfolded\b', 'I unfolded'),
        (r'\bIwrap\b', 'I wrap'),
        (r'\bIwrapped\b', 'I wrapped'),
        (r'\bIunwrap\b', 'I unwrap'),
        (r'\bIunwrapped\b', 'I unwrapped'),
        (r'\bIpack\b', 'I pack'),
        (r'\bIpacked\b', 'I packed'),
        (r'\bIunpack\b', 'I unpack'),
        (r'\bIunpacked\b', 'I unpacked'),
        (r'\bIload\b', 'I load'),
        (r'\bIloaded\b', 'I loaded'),
        (r'\bIunload\b', 'I unload'),
        (r'\bIunloaded\b', 'I unloaded'),
        (r'\bIfill\b', 'I fill'),
        (r'\bIfilled\b', 'I filled'),
        (r'\bIempty\b', 'I empty'),
        (r'\bIemptied\b', 'I emptied'),
        (r'\bIpour\b', 'I pour'),
        (r'\bIpoured\b', 'I poured'),
        (r'\bIspill\b', 'I spill'),
        (r'\bIspilled\b', 'I spilled'),
        (r'\bIleak\b', 'I leak'),
        (r'\bIleaked\b', 'I leaked'),
        (r'\bIflow\b', 'I flow'),
        (r'\bIflowed\b', 'I flowed'),
        (r'\bIdrip\b', 'I drip'),
        (r'\bIdripped\b', 'I dripped'),
        (r'\bIsplash\b', 'I splash'),
        (r'\bIsplashed\b', 'I splashed'),
        (r'\bIspray\b', 'I spray'),
        (r'\bIsprayed\b', 'I sprayed'),
        (r'\bIsquirt\b', 'I squirt'),
        (r'\bIsquirted\b', 'I squirted'),
        (r'\bIcut\b', 'I cut'),
        (r'\bIslice\b', 'I slice'),
        (r'\bIsliced\b', 'I sliced'),
        (r'\bIchop\b', 'I chop'),
        (r'\bIchopped\b', 'I chopped'),
        (r'\bIdice\b', 'I dice'),
        (r'\bIdiced\b', 'I diced'),
        (r'\bImince\b', 'I mince'),
        (r'\bIminced\b', 'I minced'),
        (r'\bIgrate\b', 'I grate'),
        (r'\bIgrated\b', 'I grated'),
        (r'\bIpeel\b', 'I peel'),
        (r'\bIpeeled\b', 'I peeled'),
        (r'\bIskin\b', 'I skin'),
        (r'\bIskinned\b', 'I skinned'),
        (r'\bIcore\b', 'I core'),
        (r'\bIcored\b', 'I cored'),
        (r'\bIseed\b', 'I seed'),
        (r'\bIseeded\b', 'I seeded'),
        (r'\bIpit\b', 'I pit'),
        (r'\bIpitted\b', 'I pitted'),
        (r'\bIbone\b', 'I bone'),
        (r'\bIboned\b', 'I boned'),
        (r'\bIfilet\b', 'I filet'),
        (r'\bIfileted\b', 'I fileted'),
        (r'\bIdebone\b', 'I debone'),
        (r'\bIdeboned\b', 'I deboned'),
        (r'\bIbutcher\b', 'I butcher'),
        (r'\bIbutchered\b', 'I butchered'),
        (r'\bIcarve\b', 'I carve'),
        (r'\bIcarved\b', 'I carved'),
        (r'\bItrim\b', 'I trim'),
        (r'\bItrimmed\b', 'I trimmed'),
        (r'\bIprune\b', 'I prune'),
        (r'\bIpruned\b', 'I pruned'),
        (r'\bIclip\b', 'I clip'),
        (r'\bIclipped\b', 'I clipped'),
        (r'\bIsnip\b', 'I snip'),
        (r'\bIsnipped\b', 'I snipped'),
        (r'\bIshave\b', 'I shave'),
        (r'\bIshaved\b', 'I shaved'),
        (r'\bIshear\b', 'I shear'),
        (r'\bIsheared\b', 'I sheared'),
        (r'\bImow\b', 'I mow'),
        (r'\bImowed\b', 'I mowed'),
        (r'\bImown\b', 'I mown'),
        (r'\bIreap\b', 'I reap'),
        (r'\bIreaped\b', 'I reaped'),
        (r'\bIharvest\b', 'I harvest'),
        (r'\bIharvested\b', 'I harvested'),
        (r'\bIgather\b', 'I gather'),
        (r'\bIgathered\b', 'I gathered'),
        (r'\bIcollect\b', 'I collect'),
        (r'\bIcollected\b', 'I collected'),
        (r'\bIpick\b', 'I pick'),
        (r'\bIpicked\b', 'I picked'),
        (r'\bIpluck\b', 'I pluck'),
        (r'\bIplucked\b', 'I plucked'),
        (r'\bIpull out\b', 'I pull out'),
        (r'\bIpulled out\b', 'I pulled out'),
        (r'\bIyank\b', 'I yank'),
        (r'\bIyanked\b', 'I yanked'),
        (r'\bIjerk\b', 'I jerk'),
        (r'\bIjerked\b', 'I jerked'),
        (r'\bItug\b', 'I tug'),
        (r'\bItugged\b', 'I tugged'),
        (r'\bIdrag\b', 'I drag'),
        (r'\bIdragged\b', 'I dragged'),
        (r'\bIhaul\b', 'I haul'),
        (r'\bIhauled\b', 'I hauled'),
        (r'\bItow\b', 'I tow'),
        (r'\bItowed\b', 'I towed'),
        (r'\bItransport\b', 'I transport'),
        (r'\bItransported\b', 'I transported'),
        (r'\bImove\b', 'I move'),
        (r'\bImoved\b', 'I moved'),
        (r'\bIshift\b', 'I shift'),
        (r'\bIshifted\b', 'I shifted'),
        (r'\bIslide\b', 'I slide'),
        (r'\bIslid\b', 'I slid'),
        (r'\bIroll\b', 'I roll'),
        (r'\bIrolled\b', 'I rolled'),
        (r'\bIspin\b', 'I spin'),
        (r'\bIspun\b', 'I spun'),
        (r'\bIrotate\b', 'I rotate'),
        (r'\bIrotated\b', 'I rotated'),
        (r'\bIrevolve\b', 'I revolve'),
        (r'\bIrevolved\b', 'I revolved'),
        (r'\bIcircle\b', 'I circle'),
        (r'\bIcircled\b', 'I circled'),
        (r'\bIorbit\b', 'I orbit'),
        (r'\bIorbited\b', 'I orbited'),
        (r'\bIswing\b', 'I swing'),
        (r'\bIswung\b', 'I swung'),
        (r'\bIsway\b', 'I sway'),
        (r'\bIswayed\b', 'I swayed'),
        (r'\bIrock\b', 'I rock'),
        (r'\bIrocked\b', 'I rocked'),
        (r'\bIshake\b', 'I shake'),
        (r'\bIshook\b', 'I shook'),
        (r'\bIvibrate\b', 'I vibrate'),
        (r'\bIvibrated\b', 'I vibrated'),
        (r'\bItremble\b', 'I tremble'),
        (r'\bItrembled\b', 'I trembled'),
        (r'\bIshiver\b', 'I shiver'),
        (r'\bIshivered\b', 'I shivered'),
        (r'\bIshudder\b', 'I shudder'),
        (r'\bIshuddered\b', 'I shuddered'),
        (r'\bIquake\b', 'I quake'),
        (r'\bIquaked\b', 'I quaked'),
        (r'\bIquiver\b', 'I quiver'),
        (r'\bIquivered\b', 'I quivered'),
        (r'\bIwobble\b', 'I wobble'),
        (r'\bIwobbled\b', 'I wobbled'),
        (r'\bItotter\b', 'I totter'),
        (r'\bItottered\b', 'I tottered'),
        (r'\bIstagger\b', 'I stagger'),
        (r'\bIstaggered\b', 'I staggered'),
        (r'\bIstumble\b', 'I stumble'),
        (r'\bIstumbled\b', 'I stumbled'),
        (r'\bItrip\b', 'I trip'),
        (r'\bItripped\b', 'I tripped'),
        (r'\bIslip\b', 'I slip'),
        (r'\bIslipped\b', 'I slipped'),
        (r'\bIskid\b', 'I skid'),
        (r'\bIskidded\b', 'I skidded'),
        (r'\bIslide\b', 'I slide'),
        (r'\bIslid\b', 'I slid'),
        (r'\bIglide\b', 'I glide'),
        (r'\bIglided\b', 'I glided'),
        (r'\bIsoar\b', 'I soar'),
        (r'\bIsoared\b', 'I soared'),
        (r'\bIhover\b', 'I hover'),
        (r'\bIhovered\b', 'I hovered'),
        (r'\bIfloat\b', 'I float'),
        (r'\bIfloated\b', 'I floated'),
        (r'\bIsink\b', 'I sink'),
        (r'\bIsank\b', 'I sank'),
        (r'\bIsunk\b', 'I sunk'),
        (r'\bIdrown\b', 'I drown'),
        (r'\bIdrowned\b', 'I drowned'),
        (r'\bIsubmerge\b', 'I submerge'),
        (r'\bIsubmerged\b', 'I submerged'),
        (r'\bIdive\b', 'I dive'),
        (r'\bIdived\b', 'I dived'),
        (r'\bIdove\b', 'I dove'),
        (r'\bIplunge\b', 'I plunge'),
        (r'\bIplunged\b', 'I plunged'),
        (r'\bIsurface\b', 'I surface'),
        (r'\bIsurfaced\b', 'I surfaced'),
        (r'\bIemerge\b', 'I emerge'),
        (r'\bIemerged\b', 'I emerged'),
        (r'\bIappear\b', 'I appear'),
        (r'\bIappeared\b', 'I appeared'),
        (r'\bIdisappear\b', 'I disappear'),
        (r'\bIdisappeared\b', 'I disappeared'),
        (r'\bIvanish\b', 'I vanish'),
        (r'\bIvanished\b', 'I vanished'),
        (r'\bIfade\b', 'I fade'),
        (r'\bIfaded\b', 'I faded'),
        (r'\bIdissolve\b', 'I dissolve'),
        (r'\bIdissolved\b', 'I dissolved'),
        (r'\bImelt\b', 'I melt'),
        (r'\bImelted\b', 'I melted'),
        (r'\bIfreeze\b', 'I freeze'),
        (r'\bIfroze\b', 'I froze'),
        (r'\bIfrozen\b', 'I frozen'),
        (r'\bIthaw\b', 'I thaw'),
        (r'\bIthawed\b', 'I thawed'),
        (r'\bIdefrost\b', 'I defrost'),
        (r'\bIdefrosted\b', 'I defrosted'),
        (r'\bIchill\b', 'I chill'),
        (r'\bIchilled\b', 'I chilled'),
        (r'\bIcool\b', 'I cool'),
        (r'\bIcooled\b', 'I cooled'),
        (r'\bIwarm\b', 'I warm'),
        (r'\bIwarmed\b', 'I warmed'),
        (r'\bIheat\b', 'I heat'),
        (r'\bIheated\b', 'I heated'),
        (r'\bIboil\b', 'I boil'),
        (r'\bIboiled\b', 'I boiled'),
        (r'\bIsimmer\b', 'I simmer'),
        (r'\bIsimmered\b', 'I simmered'),
        (r'\bIsteam\b', 'I steam'),
        (r'\bIsteamed\b', 'I steamed'),
        (r'\bIfry\b', 'I fry'),
        (r'\bIfried\b', 'I fried'),
        (r'\bIsauté\b', 'I sauté'),
        (r'\bIsautéed\b', 'I sautéed'),
        (r'\bIstir-fry\b', 'I stir-fry'),
        (r'\bIstir-fried\b', 'I stir-fried'),
        (r'\bIgrill\b', 'I grill'),
        (r'\bIgrilled\b', 'I grilled'),
        (r'\bIbarbecue\b', 'I barbecue'),
        (r'\bIbarbecued\b', 'I barbecued'),
        (r'\bIroast\b', 'I roast'),
        (r'\bIroasted\b', 'I roasted'),
        (r'\bIbroil\b', 'I broil'),
        (r'\bIbroiled\b', 'I broiled'),
        (r'\bIbraise\b', 'I braise'),
        (r'\bIbraised\b', 'I braised'),
        (r'\bIstew\b', 'I stew'),
        (r'\bIstewed\b', 'I stewed'),
        (r'\bIpoach\b', 'I poach'),
        (r'\bIpoached\b', 'I poached'),
        (r'\bIscramble\b', 'I scramble'),
        (r'\bIscrambled\b', 'I scrambled'),
        (r'\bIwhip\b', 'I whip'),
        (r'\bIwhipped\b', 'I whipped'),
        (r'\bIbeat\b', 'I beat'),
        (r'\bIbeaten\b', 'I beaten'),
        (r'\bImix\b', 'I mix'),
        (r'\bImixed\b', 'I mixed'),
        (r'\bIblend\b', 'I blend'),
        (r'\bIblended\b', 'I blended'),
        (r'\bIstir\b', 'I stir'),
        (r'\bIstirred\b', 'I stirred'),
        (r'\bIfold\b', 'I fold'),
        (r'\bIfolded\b', 'I folded'),
        (r'\bIknead\b', 'I knead'),
        (r'\bIkneaded\b', 'I kneaded'),
        (r'\bIroll out\b', 'I roll out'),
        (r'\bIrolled out\b', 'I rolled out'),
        (r'\bIflatten\b', 'I flatten'),
        (r'\bIflattened\b', 'I flattened'),
        (r'\bIpress\b', 'I press'),
        (r'\bIpressed\b', 'I pressed'),
        (r'\bIsquash\b', 'I squash'),
        (r'\bIsquashed\b', 'I squashed'),
        (r'\bIcrush\b', 'I crush'),
        (r'\bIcrushed\b', 'I crushed'),
        (r'\bImash\b', 'I mash'),
        (r'\bImashed\b', 'I mashed'),
        (r'\bIpound\b', 'I pound'),
        (r'\bIpounded\b', 'I pounded'),
        (r'\bIpulverize\b', 'I pulverize'),
        (r'\bIpulverized\b', 'I pulverized'),
        (r'\bIgrind\b', 'I grind'),
        (r'\bIground\b', 'I ground'),
        (r'\bIchurn\b', 'I churn'),
        (r'\bIchurned\b', 'I churned'),
        (r'\bIsift\b', 'I sift'),
        (r'\bIsifted\b', 'I sifted'),
        (r'\bIstrain\b', 'I strain'),
        (r'\bIstrained\b', 'I strained'),
        (r'\bIfilter\b', 'I filter'),
        (r'\bIfiltered\b', 'I filtered'),
        (r'\bIseparate\b', 'I separate'),
        (r'\bIseparated\b', 'I separated'),
        (r'\bIsort\b', 'I sort'),
        (r'\bIsorted\b', 'I sorted'),
        (r'\bIorganize\b', 'I organize'),
        (r'\bIorganized\b', 'I organized'),
        (r'\bIarrange\b', 'I arrange'),
        (r'\bIarranged\b', 'I arranged'),
        (r'\bIorder\b', 'I order'),
        (r'\bIordered\b', 'I ordered'),
        (r'\bIrank\b', 'I rank'),
        (r'\bIranked\b', 'I ranked'),
        (r'\bIclassify\b', 'I classify'),
        (r'\bIclassified\b', 'I classified'),
        (r'\bIcategorize\b', 'I categorize'),
        (r'\bIcategorized\b', 'I categorized'),
        (r'\bIgroup\b', 'I group'),
        (r'\bIgrouped\b', 'I grouped'),
        (r'\bIassemble\b', 'I assemble'),
        (r'\bIassembled\b', 'I assembled'),
        (r'\bIgather\b', 'I gather'),
        (r'\bIgathered\b', 'I gathered'),
        (r'\bIjoin\b', 'I join'),
        (r'\bIjoined\b', 'I joined'),
        (r'\bIconnect\b', 'I connect'),
        (r'\bIconnected\b', 'I connected'),
        (r'\bIlink\b', 'I link'),
        (r'\bIlinked\b', 'I linked'),
        (r'\bIattach\b', 'I attach'),
        (r'\bIattached\b', 'I attached'),
        (r'\bIfasten\b', 'I fasten'),
        (r'\bIfastened\b', 'I fastened'),
        (r'\bIsecure\b', 'I secure'),
        (r'\bIsecured\b', 'I secured'),
        (r'\bIanchor\b', 'I anchor'),
        (r'\bIanchored\b', 'I anchored'),
        (r'\bImoor\b', 'I moor'),
        (r'\bImoored\b', 'I moored'),
        (r'\bItie\b', 'I tie'),
        (r'\bItied\b', 'I tied'),
        (r'\bIbind\b', 'I bind'),
        (r'\bIbound\b', 'I bound'),
        (r'\bIlash\b', 'I lash'),
        (r'\bIlashed\b', 'I lashed'),
        (r'\bIstrap\b', 'I strap'),
        (r'\bIstrapped\b', 'I strapped'),
        (r'\bIbelt\b', 'I belt'),
        (r'\bIbelted\b', 'I belted'),
        (r'\bIbuckle\b', 'I buckle'),
        (r'\bIbuckled\b', 'I buckled'),
        (r'\bIzip\b', 'I zip'),
        (r'\bIzipped\b', 'I zipped'),
        (r'\bIbutton\b', 'I button'),
        (r'\bIbuttoned\b', 'I buttoned'),
        (r'\bIsnap\b', 'I snap'),
        (r'\bIsnapped\b', 'I snapped'),
        (r'\bIvelcro\b', 'I velcro'),
        (r'\bIvelcroed\b', 'I velcroed'),
        (r'\bIpin\b', 'I pin'),
        (r'\bIpinned\b', 'I pinned'),
        (r'\bIclip\b', 'I clip'),
        (r'\bIclipped\b', 'I clipped'),
        (r'\bIstaple\b', 'I staple'),
        (r'\bIstapled\b', 'I stapled'),
        (r'\bItack\b', 'I tack'),
        (r'\bItacked\b', 'I tacked'),
        (r'\bInail\b', 'I nail'),
        (r'\bInailed\b', 'I nailed'),
        (r'\bIhammer\b', 'I hammer'),
        (r'\bIhammered\b', 'I hammered'),
        (r'\bIscrew\b', 'I screw'),
        (r'\bIscrewed\b', 'I screwed'),
        (r'\bIbolt\b', 'I bolt'),
        (r'\bIbolted\b', 'I bolted'),
        (r'\bIrivet\b', 'I rivet'),
        (r'\bIriveted\b', 'I riveted'),
        (r'\bIweld\b', 'I weld'),
        (r'\bIwelded\b', 'I welded'),
        (r'\bIsolder\b', 'I solder'),
        (r'\bIsoldered\b', 'I soldered'),
        (r'\bIbraze\b', 'I braze'),
        (r'\bIbrazed\b', 'I brazed'),
        (r'\bIglue\b', 'I glue'),
        (r'\bIglued\b', 'I glued'),
        (r'\bIpaste\b', 'I paste'),
        (r'\bIpasted\b', 'I pasted'),
        (r'\bIcement\b', 'I cement'),
        (r'\bIcemented\b', 'I cemented'),
        (r'\bIseal\b', 'I seal'),
        (r'\bIsealed\b', 'I sealed'),
        (r'\bIcaulk\b', 'I caulk'),
        (r'\bIcaulked\b', 'I caulked'),
        (r'\bIplug\b', 'I plug'),
        (r'\bIplugged\b', 'I plugged'),
        (r'\bIstop up\b', 'I stop up'),
        (r'\bIstopped up\b', 'I stopped up'),
        (r'\bIblock\b', 'I block'),
        (r'\bIblocked\b', 'I blocked'),
        (r'\bIobstruct\b', 'I obstruct'),
        (r'\bIobstructed\b', 'I obstructed'),
        (r'\bIclog\b', 'I clog'),
        (r'\bIclogged\b', 'I clogged'),
        (r'\bIjam\b', 'I jam'),
        (r'\bIjammed\b', 'I jammed'),
        (r'\bIstuff\b', 'I stuff'),
        (r'\bIstuffed\b', 'I stuffed'),
        (r'\bIcram\b', 'I cram'),
        (r'\bIcrammed\b', 'I crammed'),
        (r'\bIsqueeze in\b', 'I squeeze in'),
        (r'\bIsqueezed in\b', 'I squeezed in'),
        (r'\bIwedge\b', 'I wedge'),
        (r'\bIwedged\b', 'I wedged'),
        (r'\bIforce\b', 'I force'),
        (r'\bIforced\b', 'I forced'),
        (r'\bIshove\b', 'I shove'),
        (r'\bIshoved\b', 'I shoved'),
        (r'\bIram\b', 'I ram'),
        (r'\bIrammed\b', 'I rammed'),
        (r'\bIslam\b', 'I slam'),
        (r'\bIslammed\b', 'I slammed'),
        (r'\bIbang\b', 'I bang'),
        (r'\bIbanged\b', 'I banged'),
        (r'\bIwhack\b', 'I whack'),
        (r'\bIwhacked\b', 'I whacked'),
        (r'\bIthump\b', 'I thump'),
        (r'\bIthumped\b', 'I thumped'),
        (r'\bIpound\b', 'I pound'),
        (r'\bIpounded\b', 'I pounded'),
        (r'\bIbeat\b', 'I beat'),
        (r'\bIbeaten\b', 'I beaten'),
        (r'\bIsmash\b', 'I smash'),
        (r'\bIsmashed\b', 'I smashed'),
        (r'\bIshatter\b', 'I shatter'),
        (r'\bIshattered\b', 'I shattered'),
        (r'\bIcrack\b', 'I crack'),
        (r'\bIcracked\b', 'I cracked'),
        (r'\bIsplit\b', 'I split'),
        (r'\bIchip\b', 'I chip'),
        (r'\bIchipped\b', 'I chipped'),
        (r'\bIbreak\b', 'I break'),
        (r'\bIbroke\b', 'I broke'),
        (r'\bIbreak down\b', 'I break down'),
        (r'\bIbroke down\b', 'I broke down'),
        (r'\bImalfunction\b', 'I malfunction'),
        (r'\bImalfunctioned\b', 'I malfunctioned'),
        (r'\bIfail\b', 'I fail'),
        (r'\bIfailed\b', 'I failed'),
        (r'\bIstop working\b', 'I stop working'),
        (r'\bIstopped working\b', 'I stopped working'),
        (r'\bIjam\b', 'I jam'),
        (r'\bIjammed\b', 'I jammed'),
        (r'\bIfreeze up\b', 'I freeze up'),
        (r'\bIfroze up\b', 'I froze up'),
        (r'\bIcrash\b', 'I crash'),
        (r'\bIcrashed\b', 'I crashed'),
        (r'\bIerror\b', 'I error'),
        (r'\bIerrored\b', 'I errored'),
        (r'\bIglitch\b', 'I glitch'),
        (r'\bIglitched\b', 'I glitched'),
        (r'\bIbug\b', 'I bug'),
        (r'\bIbugged\b', 'I bugged'),
        (r'\bIfreeze\b', 'I freeze'),
        (r'\bIfroze\b', 'I froze'),
        (r'\bIhang\b', 'I hang'),
        (r'\bIhung\b', 'I hung'),
        (r'\bIstall\b', 'I stall'),
        (r'\bIstalled\b', 'I stalled'),
        (r'\bIlag\b', 'I lag'),
        (r'\bIlagged\b', 'I lagged'),
        (r'\bIslow down\b', 'I slow down'),
        (r'\bIslowed down\b', 'I slowed down'),
        (r'\bIspeed up\b', 'I speed up'),
        (r'\bIsped up\b', 'I sped up'),
        (r'\bIaccelerate\b', 'I accelerate'),
        (r'\bIaccelerated\b', 'I accelerated'),
        (r'\bIdecelerate\b', 'I decelerate'),
        (r'\bIdecelerated\b', 'I decelerated'),
        (r'\bIbrake\b', 'I brake'),
        (r'\bIbraked\b', 'I braked'),
        (r'\bIcoast\b', 'I coast'),
        (r'\bIcoasted\b', 'I coasted'),
        (r'\bIcruise\b', 'I cruise'),
        (r'\bIcruised\b', 'I cruised'),
        (r'\bIrace\b', 'I race'),
        (r'\bIraced\b', 'I raced'),
        (r'\bIsprint\b', 'I sprint'),
        (r'\bIsprinted\b', 'I sprinted'),
        (r'\bIdash\b', 'I dash'),
        (r'\bIdashed\b', 'I dashed'),
        (r'\bIbolt\b', 'I bolt'),
        (r'\bIbolted\b', 'I bolted'),
        (r'\bIzoom\b', 'I zoom'),
        (r'\bIzoomed\b', 'I zoomed'),
        (r'\bIwhiz\b', 'I whiz'),
        (r'\bIwhizzed\b', 'I whizzed'),
        (r'\bIzip\b', 'I zip'),
        (r'\bIzipped\b', 'I zipped'),
        (r'\bIfly\b', 'I fly'),
        (r'\bIflew\b', 'I flew'),
        (r'\bIsoar\b', 'I soar'),
        (r'\bIsoared\b', 'I soared'),
        (r'\bIglide\b', 'I glide'),
        (r'\bIglided\b', 'I glided'),
        (r'\bIcreep\b', 'I creep'),
        (r'\bIcrept\b', 'I crept'),
        (r'\bIcrawl\b', 'I crawl'),
        (r'\bIcrawled\b', 'I crawled'),
        (r'\bIslither\b', 'I slither'),
        (r'\bIslithered\b', 'I slithered'),
        (r'\bIwriggle\b', 'I wriggle'),
        (r'\bIwriggled\b', 'I wriggled'),
        (r'\bIsquirm\b', 'I squirm'),
        (r'\bIsquirmed\b', 'I squirmed'),
        (r'\bIwiggle\b', 'I wiggle'),
        (r'\bIwiggled\b', 'I wiggled'),
        (r'\bIjiggle\b', 'I jiggle'),
        (r'\bIjiggled\b', 'I jiggled'),
        (r'\bIbounce\b', 'I bounce'),
        (r'\bIbounced\b', 'I bounced'),
        (r'\bIhop\b', 'I hop'),
        (r'\bIhopped\b', 'I hopped'),
        (r'\bIskip\b', 'I skip'),
        (r'\bIskipped\b', 'I skipped'),
        (r'\bIleap\b', 'I leap'),
        (r'\bIleaped\b', 'I leaped'),
        (r'\bIleapt\b', 'I leapt'),
        (r'\bIbound\b', 'I bound'),
        (r'\bIvault\b', 'I vault'),
        (r'\bIvaulted\b', 'I vaulted'),
        (r'\bIpounce\b', 'I pounce'),
        (r'\bIpounced\b', 'I pounced'),
        (r'\bIlunge\b', 'I lunge'),
        (r'\bIlunged\b', 'I lunged'),
        (r'\bIdive\b', 'I dive'),
        (r'\bIdived\b', 'I dived'),
        (r'\bIdove\b', 'I dove'),
        (r'\bIplunge\b', 'I plunge'),
        (r'\bIplunged\b', 'I plunged'),
        (r'\bIjump\b', 'I jump'),
        (r'\bIjumped\b', 'I jumped'),
        (r'\bIspring\b', 'I spring'),
        (r'\bIsprang\b', 'I sprang'),
        (r'\bIsprung\b', 'I sprung'),
        (r'\bIlaunch\b', 'I launch'),
        (r'\bIlaunched\b', 'I launched'),
        (r'\bIcatapult\b', 'I catapult'),
        (r'\bIcatapulted\b', 'I catapulted'),
        (r'\bIhurl\b', 'I hurl'),
        (r'\bIhurled\b', 'I hurled'),
        (r'\bIfling\b', 'I fling'),
        (r'\bIflung\b', 'I flung'),
        (r'\bItoss\b', 'I toss'),
        (r'\bItossed\b', 'I tossed'),
        (r'\bIlob\b', 'I lob'),
        (r'\bIlobbed\b', 'I lobbed'),
        (r'\bIheave\b', 'I heave'),
        (r'\bIheaved\b', 'I heaved'),
        (r'\bIpitch\b', 'I pitch'),
        (r'\bIpitched\b', 'I pitched'),
        (r'\bIsling\b', 'I sling'),
        (r'\bIslung\b', 'I slung'),
        (r'\bIfire\b', 'I fire'),
        (r'\bIfired\b', 'I fired'),
        (r'\bIshoot\b', 'I shoot'),
        (r'\bIshot\b', 'I shot'),
        (r'\bIaim\b', 'I aim'),
        (r'\bIaimed\b', 'I aimed'),
        (r'\bItarget\b', 'I target'),
        (r'\bItargeted\b', 'I targeted'),
        (r'\bIpoint\b', 'I point'),
        (r'\bIpointed\b', 'I pointed'),
        (r'\bIdirect\b', 'I direct'),
        (r'\bIdirected\b', 'I directed'),
        (r'\bIguide\b', 'I guide'),
        (r'\bIguided\b', 'I guided'),
        (r'\bIlead\b', 'I lead'),
        (r'\bIled\b', 'I led'),
        (r'\bIfollow\b', 'I follow'),
        (r'\bIfollowed\b', 'I followed'),
        (r'\bItrail\b', 'I trail'),
        (r'\bItrailed\b', 'I trailed'),
        (r'\bItrack\b', 'I track'),
        (r'\bItracked\b', 'I tracked'),
        (r'\bItrace\b', 'I trace'),
        (r'\bItraced\b', 'I traced'),
        (r'\bIpursue\b', 'I pursue'),
        (r'\bIpursued\b', 'I pursued'),
        (r'\bIchase\b', 'I chase'),
        (r'\bIchased\b', 'I chased'),
        (r'\bIhunt\b', 'I hunt'),
        (r'\bIhunted\b', 'I hunted'),
        (r'\bIstalk\b', 'I stalk'),
        (r'\bIstalked\b', 'I stalked'),
        (r'\bIshadow\b', 'I shadow'),
        (r'\bIshadowed\b', 'I shadowed'),
        (r'\bItail\b', 'I tail'),
        (r'\bItailed\b', 'I tailed'),
        (r'\bIspy on\b', 'I spy on'),
        (r'\bIspied on\b', 'I spied on'),
        (r'\bIwatch\b', 'I watch'),
        (r'\bIwatched\b', 'I watched'),
        (r'\bIobserve\b', 'I observe'),
        (r'\bIobserved\b', 'I observed'),
        (r'\bImonitor\b', 'I monitor'),
        (r'\bImonitored\b', 'I monitored'),
        (r'\bIsurveillance\b', 'I surveillance'),
        (r'\bIsurveilled\b', 'I surveilled'),
        (r'\bIsupervise\b', 'I supervise'),
        (r'\bIsupervised\b', 'I supervised'),
        (r'\bIoversee\b', 'I oversee'),
        (r'\bIoversaw\b', 'I oversaw'),
        (r'\bIoverseen\b', 'I overseen'),
        (r'\bImanage\b', 'I manage'),
        (r'\bImanaged\b', 'I managed'),
        (r'\bIcontrol\b', 'I control'),
        (r'\bIcontrolled\b', 'I controlled'),
        (r'\bIcommand\b', 'I command'),
        (r'\bIcommanded\b', 'I commanded'),
        (r'\bIorder\b', 'I order'),
        (r'\bIordered\b', 'I ordered'),
        (r'\bIinstruct\b', 'I instruct'),
        (r'\bIinstructed\b', 'I instructed'),
        (r'\bIteach\b', 'I teach'),
        (r'\bItaught\b', 'I taught'),
        (r'\bIeducate\b', 'I educate'),
        (r'\bIeducated\b', 'I educated'),
        (r'\bItrain\b', 'I train'),
        (r'\bItrained\b', 'I trained'),
        (r'\bIcoach\b', 'I coach'),
        (r'\bIcoached\b', 'I coached'),
        (r'\bImentor\b', 'I mentor'),
        (r'\bImentored\b', 'I mentored'),
        (r'\bItutor\b', 'I tutor'),
        (r'\bItutored\b', 'I tutored'),
        (r'\bIadvise\b', 'I advise'),
        (r'\bIadvised\b', 'I advised'),
        (r'\bIcounsel\b', 'I counsel'),
        (r'\bIcounseled\b', 'I counseled'),
        (r'\bIconsult\b', 'I consult'),
        (r'\bIconsulted\b', 'I consulted'),
        (r'\bIrecommend\b', 'I recommend'),
        (r'\bIrecommended\b', 'I recommended'),
        (r'\bIsuggest\b', 'I suggest'),
        (r'\bIsuggested\b', 'I suggested'),
        (r'\bIpropose\b', 'I propose'),
        (r'\bIproposed\b', 'I proposed'),
        (r'\bIoffer\b', 'I offer'),
        (r'\bIoffered\b', 'I offered'),
        (r'\bIpresent\b', 'I present'),
        (r'\bIpresented\b', 'I presented'),
        (r'\bIsubmit\b', 'I submit'),
        (r'\bIsubmitted\b', 'I submitted'),
        (r'\bIdeliver\b', 'I deliver'),
        (r'\bIdelivered\b', 'I delivered'),
        (r'\bIprovide\b', 'I provide'),
        (r'\bIprovided\b', 'I provided'),
        (r'\bIsupply\b', 'I supply'),
        (r'\bIsupplied\b', 'I supplied'),
        (r'\bIfurnish\b', 'I furnish'),
        (r'\bIfurnished\b', 'I furnished'),
        (r'\bIequip\b', 'I equip'),
        (r'\bIequipped\b', 'I equipped'),
        (r'\bIarm\b', 'I arm'),
        (r'\bIarmed\b', 'I armed'),
        (r'\bIoutfit\b', 'I outfit'),
        (r'\bIoutfitted\b', 'I outfitted'),
        (r'\bIrig\b', 'I rig'),
        (r'\bIrigged\b', 'I rigged'),
        (r'\bIfit\b', 'I fit'),
        (r'\bIfitted\b', 'I fitted'),
        (r'\bIinstall\b', 'I install'),
        (r'\bIinstalled\b', 'I installed'),
        (r'\bImount\b', 'I mount'),
        (r'\bImounted\b', 'I mounted'),
        (r'\bIassemble\b', 'I assemble'),
        (r'\bIassembled\b', 'I assembled'),
        (r'\bIconstruct\b', 'I construct'),
        (r'\bIconstructed\b', 'I constructed'),
        (r'\bIerect\b', 'I erect'),
        (r'\bIerected\b', 'I erected'),
        (r'\bIraise\b', 'I raise'),
        (r'\bIraised\b', 'I raised'),
        (r'\bIlift\b', 'I lift'),
        (r'\bIlifted\b', 'I lifted'),
        (r'\bIhoist\b', 'I hoist'),
        (r'\bIhoisted\b', 'I hoisted'),
        (r'\bIelevate\b', 'I elevate'),
        (r'\bIelevated\b', 'I elevated'),
        (r'\bIboost\b', 'I boost'),
        (r'\bIboosted\b', 'I boosted'),
        (r'\bIjack up\b', 'I jack up'),
        (r'\bIjacked up\b', 'I jacked up'),
        (r'\bIlower\b', 'I lower'),
        (r'\bIlowered\b', 'I lowered'),
        (r'\bIdrop\b', 'I drop'),
        (r'\bIdropped\b', 'I dropped'),
        (r'\bIreduce\b', 'I reduce'),
        (r'\bIreduced\b', 'I reduced'),
        (r'\bIdecrease\b', 'I decrease'),
        (r'\bIdecreased\b', 'I decreased'),
        (r'\bIdiminish\b', 'I diminish'),
        (r'\bIdiminished\b', 'I diminished'),
        (r'\bIlessen\b', 'I lessen'),
        (r'\bIlessened\b', 'I lessened'),
        (r'\bIcut\b', 'I cut'),
        (r'\bIslash\b', 'I slash'),
        (r'\bIslashed\b', 'I slashed'),
        (r'\bItrim\b', 'I trim'),
        (r'\bItrimmed\b', 'I trimmed'),
        (r'\bIprune\b', 'I prune'),
        (r'\bIpruned\b', 'I pruned'),
        (r'\bIshorten\b', 'I shorten'),
        (r'\bIshortened\b', 'I shortened'),
        (r'\bIabridge\b', 'I abridge'),
        (r'\bIabridged\b', 'I abridged'),
        (r'\bIcondense\b', 'I condense'),
        (r'\bIcondensed\b', 'I condensed'),
        (r'\bIcompress\b', 'I compress'),
        (r'\bIcompressed\b', 'I compressed'),
        (r'\bIsquash\b', 'I squash'),
        (r'\bIsquashed\b', 'I squashed'),
        (r'\bIcrush\b', 'I crush'),
        (r'\bIcrushed\b', 'I crushed'),
        (r'\bIcompact\b', 'I compact'),
        (r'\bIcompacted\b', 'I compacted'),
        (r'\bIconcentrate\b', 'I concentrate'),
        (r'\bIconcentrated\b', 'I concentrated'),
        (r'\bIintensify\b', 'I intensify'),
        (r'\bIintensified\b', 'I intensified'),
        (r'\bIamplify\b', 'I amplify'),
        (r'\bIamplified\b', 'I amplified'),
        (r'\bImagnify\b', 'I magnify'),
        (r'\bImagnified\b', 'I magnified'),
        (r'\bIenlarge\b', 'I enlarge'),
        (r'\bIenlarged\b', 'I enlarged'),
        (r'\bIexpand\b', 'I expand'),
        (r'\bIexpanded\b', 'I expanded'),
        (r'\bIextend\b', 'I extend'),
        (r'\bIextended\b', 'I extended'),
        (r'\bIstretch\b', 'I stretch'),
        (r'\bIstretched\b', 'I stretched'),
        (r'\bIlengthen\b', 'I lengthen'),
        (r'\bIlengthened\b', 'I lengthened'),
        (r'\bIprolong\b', 'I prolong'),
        (r'\bIprolonged\b', 'I prolonged'),
        (r'\bIextend\b', 'I extend'),
        (r'\bIextended\b', 'I extended'),
        (r'\bIwiden\b', 'I widen'),
        (r'\bIwidened\b', 'I widened'),
        (r'\bIbroaden\b', 'I broaden'),
        (r'\bIbroadened\b', 'I broadened'),
        (r'\bIthicken\b', 'I thicken'),
        (r'\bIthickened\b', 'I thickened'),
        (r'\bIthin\b', 'I thin'),
        (r'\bIthinned\b', 'I thinned'),
        (r'\bInarrow\b', 'I narrow'),
        (r'\bInarrowed\b', 'I narrowed'),
        (r'\bItighten\b', 'I tighten'),
        (r'\bItightened\b', 'I tightened'),
        (r'\bIloosen\b', 'I loosen'),
        (r'\bIloosened\b', 'I loosened'),
        (r'\bIslacken\b', 'I slacken'),
        (r'\bIslackened\b', 'I slackened'),
        (r'\bIrelax\b', 'I relax'),
        (r'\bIrelaxed\b', 'I relaxed'),
        (r'\bIease\b', 'I ease'),
        (r'\bIeased\b', 'I eased'),
        (r'\bIrelieve\b', 'I relieve'),
        (r'\bIrelieved\b', 'I relieved'),
        (r'\bIsoothe\b', 'I soothe'),
        (r'\bIsoothed\b', 'I soothed'),
        (r'\bIcalm\b', 'I calm'),
        (r'\bIcalmed\b', 'I calmed'),
        (r'\bIquiet\b', 'I quiet'),
        (r'\bIquieted\b', 'I quieted'),
        (r'\bIsilence\b', 'I silence'),
        (r'\bIsilenced\b', 'I silenced'),
        (r'\bImute\b', 'I mute'),
        (r'\bImuted\b', 'I muted'),
        (r'\bIhush\b', 'I hush'),
        (r'\bIhushed\b', 'I hushed'),
        (r'\bIstill\b', 'I still'),
        (r'\bIstilled\b', 'I stilled'),
        (r'\bIsettle\b', 'I settle'),
        (r'\bIsettled\b', 'I settled'),
        (r'\bIstabilize\b', 'I stabilize'),
        (r'\bIstabilized\b', 'I stabilized'),
        (r'\bIsteady\b', 'I steady'),
        (r'\bIsteadied\b', 'I steadied'),
        (r'\bIbalance\b', 'I balance'),
        (r'\bIbalanced\b', 'I balanced'),
        (r'\bIlevel\b', 'I level'),
        (r'\bIleveled\b', 'I leveled'),
        (r'\bIstraighten\b', 'I straighten'),
        (r'\bIstraightened\b', 'I straightened'),
        (r'\bIalign\b', 'I align'),
        (r'\bIaligned\b', 'I aligned'),
        (r'\bIcenter\b', 'I center'),
        (r'\bIcentered\b', 'I centered'),
        (r'\bIfocus\b', 'I focus'),
        (r'\bIfocused\b', 'I focused'),
        (r'\bIconverge\b', 'I converge'),
        (r'\bIconverged\b', 'I converged'),
        (r'\bImeet\b', 'I meet'),
        (r'\bImet\b', 'I met'),
        (r'\bIintersect\b', 'I intersect'),
        (r'\bIintersected\b', 'I intersected'),
        (r'\bIcross\b', 'I cross'),
        (r'\bIcrossed\b', 'I crossed'),
        (r'\bIoverlap\b', 'I overlap'),
        (r'\bIoverlapped\b', 'I overlapped'),
        (r'\bIcoincide\b', 'I coincide'),
        (r'\bIcoincided\b', 'I coincided'),
        (r'\bIcorrespond\b', 'I correspond'),
        (r'\bIcorresponded\b', 'I corresponded'),
        (r'\bImatch\b', 'I match'),
        (r'\bImatched\b', 'I matched'),
        (r'\bIfit\b', 'I fit'),
        (r'\bIfitted\b', 'I fitted'),
        (r'\bIsuit\b', 'I suit'),
        (r'\bIsuited\b', 'I suited'),
        (r'\bIagree\b', 'I agree'),
        (r'\bIagreed\b', 'I agreed'),
        (r'\bIaccord\b', 'I accord'),
        (r'\bIaccorded\b', 'I accorded'),
        (r'\bIconform\b', 'I conform'),
        (r'\bIconformed\b', 'I conformed'),
        (r'\bIcomply\b', 'I comply'),
        (r'\bIcomplied\b', 'I complied'),
        (r'\bIobey\b', 'I obey'),
        (r'\bIobeyed\b', 'I obeyed'),
        (r'\bIfollow\b', 'I follow'),
        (r'\bIfollowed\b', 'I followed'),
        (r'\bIadhere\b', 'I adhere'),
        (r'\bIadhered\b', 'I adhered'),
        (r'\bIstick to\b', 'I stick to'),
        (r'\bIstuck to\b', 'I stuck to'),
        (r'\bIkeep to\b', 'I keep to'),
        (r'\bIkept to\b', 'I kept to'),
        (r'\bImaintain\b', 'I maintain'),
        (r'\bImaintained\b', 'I maintained'),
        (r'\bIpreserve\b', 'I preserve'),
        (r'\bIpreserved\b', 'I preserved'),
        (r'\bIconserve\b', 'I conserve'),
        (r'\bIconserved\b', 'I conserved'),
        (r'\bIprotect\b', 'I protect'),
        (r'\bIprotected\b', 'I protected'),
        (r'\bIdefend\b', 'I defend'),
        (r'\bIdefended\b', 'I defended'),
        (r'\bIguard\b', 'I guard'),
        (r'\bIguarded\b', 'I guarded'),
        (r'\bIshield\b', 'I shield'),
        (r'\bIshielded\b', 'I shielded'),
        (r'\bIshelter\b', 'I shelter'),
        (r'\bIsheltered\b', 'I sheltered'),
        (r'\bIcover\b', 'I cover'),
        (r'\bIcovered\b', 'I covered'),
        (r'\bIhide\b', 'I hide'),
        (r'\bIhid\b', 'I hid'),
        (r'\bIhidden\b', 'I hidden'),
        (r'\bIconceal\b', 'I conceal'),
        (r'\bIconcealed\b', 'I concealed'),
        (r'\bImask\b', 'I mask'),
        (r'\bImasked\b', 'I masked'),
        (r'\bIdisguise\b', 'I disguise'),
        (r'\bIdisguised\b', 'I disguised'),
        (r'\bIcamouflage\b', 'I camouflage'),
        (r'\bIcamouflaged\b', 'I camouflaged'),
        (r'\bIcloak\b', 'I cloak'),
        (r'\bIcloaked\b', 'I cloaked'),
        (r'\bIveil\b', 'I veil'),
        (r'\bIveiled\b', 'I veiled'),
        (r'\bIwrap\b', 'I wrap'),
        (r'\bIwrapped\b', 'I wrapped'),
        (r'\bIenvelop\b', 'I envelop'),
        (r'\bIenveloped\b', 'I enveloped'),
        (r'\bIencapsulate\b', 'I encapsulate'),
        (r'\bIencapsulated\b', 'I encapsulated'),
        (r'\bIencase\b', 'I encase'),
        (r'\bIencased\b', 'I encased'),
        (r'\bIenclose\b', 'I enclose'),
        (r'\bIenclosed\b', 'I enclosed'),
        (r'\bIsurround\b', 'I surround'),
        (r'\bIsurrounded\b', 'I surrounded'),
        (r'\bIencircle\b', 'I encircle'),
        (r'\bIencircled\b', 'I encircled'),
        (r'\bIring\b', 'I ring'),
        (r'\bIrang\b', 'I rang'),
        (r'\bIrung\b', 'I rung'),
        (r'\bIborder\b', 'I border'),
        (r'\bIbordered\b', 'I bordered'),
        (r'\bIedge\b', 'I edge'),
        (r'\bIedged\b', 'I edged'),
        (r'\bIrim\b', 'I rim'),
        (r'\bIrimmed\b', 'I rimmed'),
        (r'\bIframe\b', 'I frame'),
        (r'\bIframed\b', 'I framed'),
        (r'\bIoutline\b', 'I outline'),
        (r'\bIoutlined\b', 'I outlined'),
        (r'\bIdelineate\b', 'I delineate'),
        (r'\bIdelineated\b', 'I delineated'),
        (r'\bIdefine\b', 'I define'),
        (r'\bIdefined\b', 'I defined'),
        (r'\bIdemarcate\b', 'I demarcate'),
        (r'\bIdemarcated\b', 'I demarcated'),
        (r'\bIdelimit\b', 'I delimit'),
        (r'\bIdelimited\b', 'I delimited'),
        (r'\bIboundary\b', 'I boundary'),
        (r'\bIboundary\b', 'I boundaried'),
        (r'\bIlimit\b', 'I limit'),
        (r'\bIlimited\b', 'I limited'),
        (r'\bIrestrict\b', 'I restrict'),
        (r'\bIrestricted\b', 'I restricted'),
        (r'\bIconfine\b', 'I confine'),
        (r'\bIconfined\b', 'I confined'),
        (r'\bIcontain\b', 'I contain'),
        (r'\bIcontained\b', 'I contained'),
        (r'\bIrestrain\b', 'I restrain'),
        (r'\bIrestrained\b', 'I restrained'),
        (r'\bIcurb\b', 'I curb'),
        (r'\bIcurbed\b', 'I curbed'),
        (r'\bIcheck\b', 'I check'),
        (r'\bIchecked\b', 'I checked'),
        (r'\bIinhibit\b', 'I inhibit'),
        (r'\bIinhibited\b', 'I inhibited'),
        (r'\bIsuppress\b', 'I suppress'),
        (r'\bIsuppressed\b', 'I suppressed'),
        (r'\bIrepress\b', 'I repress'),
        (r'\bIrepressed\b', 'I repressed'),
        (r'\bIstifle\b', 'I stifle'),
        (r'\bIstifled\b', 'I stifled'),
        (r'\bIsmother\b', 'I smother'),
        (r'\bIsmothered\b', 'I smothered'),
        (r'\bIsuffocate\b', 'I suffocate'),
        (r'\bIsuffocated\b', 'I suffocated'),
        (r'\bIchoke\b', 'I choke'),
        (r'\bIchoked\b', 'I choked'),
        (r'\bIstrangle\b', 'I strangle'),
        (r'\bIstrangled\b', 'I strangled'),
        (r'\bIthrottle\b', 'I throttle'),
        (r'\bIthrottled\b', 'I throttled'),
        (r'\bIsqueeze\b', 'I squeeze'),
        (r'\bIsqueezed\b', 'I squeezed'),
        (r'\bIcompress\b', 'I compress'),
        (r'\bIcompressed\b', 'I compressed'),
        (r'\bIcrush\b', 'I crush'),
        (r'\bIcrushed\b', 'I crushed'),
        (r'\bIsquash\b', 'I squash'),
        (r'\bIsquashed\b', 'I squashed'),
        (r'\bIpress\b', 'I press'),
        (r'\bIpressed\b', 'I pressed'),
        (r'\bIpush\b', 'I push'),
        (r'\bIpushed\b', 'I pushed'),
        (r'\bIshove\b', 'I shove'),
        (r'\bIshoved\b', 'I shoved'),
        (r'\bInudge\b', 'I nudge'),
        (r'\bInudged\b', 'I nudged'),
        (r'\bIbump\b', 'I bump'),
        (r'\bIbumped\b', 'I bumped'),
        (r'\bIjolt\b', 'I jolt'),
        (r'\bIjolted\b', 'I jolted'),
        (r'\bIjerk\b', 'I jerk'),
        (r'\bIjerked\b', 'I jerked'),
        (r'\bIyank\b', 'I yank'),
        (r'\bIyanked\b', 'I yanked'),
        (r'\bItug\b', 'I tug'),
        (r'\bItugged\b', 'I tugged'),
        (r'\bIpull\b', 'I pull'),
        (r'\bIpulled\b', 'I pulled'),
        (r'\bIdrag\b', 'I drag'),
        (r'\bIdragged\b', 'I dragged'),
        (r'\bIhaul\b', 'I haul'),
        (r'\bIhauled\b', 'I hauled'),
        (r'\bItow\b', 'I tow'),
        (r'\bItowed\b', 'I towed'),
    ]
    
    # Apply all fixes
    for pattern, replacement in common_fixes:
        text = re.sub(pattern, replacement, text, flags=re.IGNORECASE)
    
    # Normalize whitespace
    text = re.sub(r'\s+', ' ', text)
    
    return text

def format_as_html(book_name, book_text):
    """Format book text as HTML"""
    if not book_text:
        return ""
    
    html_lines = [f"<h1 class='et'>{book_name}</h1>", "<BR>"]
    html_lines.append('<div id="contenten" style="position:relative; top:0px; left:0px; overflow:auto"><table cellpadding=0 cellspacing=0 border=0>')
    
    lines = book_text.split('\n')
    current_chapter = 1
    current_verse = 1
    
    for line in lines:
        line = line.strip()
        if not line:
            continue
        
        # Skip headers and metadata
        skip_patterns = [
            r'recognized as deuterocanonical',
            r'scripture by',
            r'roman catholic',
            r'greek orthodox',
            r'the book of',
            r'first book of',
            r'second book of',
            r'maccabees',
            r'page \d+',
            r'^\d+$'
        ]
        
        should_skip = False
        for pattern in skip_patterns:
            if re.search(pattern, line, re.IGNORECASE):
                should_skip = True
                break
        
        if should_skip:
            continue
        
        # Look for chapter:verse patterns
        cv_match = re.match(r'^(\d+):(\d+)\s+(.+)', line)
        if cv_match:
            current_chapter = int(cv_match.group(1))
            current_verse = int(cv_match.group(2))
            verse_text = cv_match.group(3).strip()
            if verse_text and len(verse_text) > 3:
                html_lines.append(f'<tr><td class="vn">{current_chapter}:{current_verse}</td><td class="vn">&nbsp;&nbsp;</td><td class="v en">{verse_text}</td></tr>')
            continue
        
        # Look for verse numbers only
        verse_match = re.match(r'^(\d+)\s+(.+)', line)
        if verse_match:
            verse_num = int(verse_match.group(1))
            verse_text = verse_match.group(2).strip()
            if verse_num <= 200 and len(verse_text) > 3:  # Reasonable verse number
                current_verse = verse_num
                html_lines.append(f'<tr><td class="vn">{current_chapter}:{current_verse}</td><td class="vn">&nbsp;&nbsp;</td><td class="v en">{verse_text}</td></tr>')
            continue
        
        # Check if it's a chapter number
        if re.match(r'^\d+$', line) and int(line) <= 50:
            current_chapter = int(line)
            current_verse = 1
            continue
        
        # Otherwise treat as continuation text
        if len(line) > 15:  # Only substantial text
            html_lines.append(f'<tr><td class="vn">{current_chapter}:{current_verse}</td><td class="vn">&nbsp;&nbsp;</td><td class="v en">{line}</td></tr>')
            current_verse += 1
    
    html_lines.append('</table></div>')
    return '\n'.join(html_lines)

def main():
    pdf_path = "eng-web-c_all.pdf"
    
    if not os.path.exists(pdf_path):
        print(f"PDF file {pdf_path} not found!")
        return
    
    print("Extracting text from PDF...")
    full_text = extract_pdf_text(pdf_path)
    
    if not full_text:
        print("Failed to extract text from PDF")
        return
    
    lines = full_text.split('\n')
    print(f"Total lines in PDF: {len(lines)}")
    
    # Extract books using known patterns and line ranges
    books_to_extract = {
        'tobit': {
            'patterns': [r'Tobit isrecognized asDeuterocanon', r'The book ofthewords ofTobit'],
            'range': (50900, 51925)
        },
        'judith': {
            'patterns': [r'Judith isrecognized asDeuterocanon', r'Inthedays ofArphaxad'],
            'range': (51925, 54674)
        },
        'wisdom': {
            'patterns': [r'Wisdom of Solomon', r'Love righteousness'],
            'range': (82324, 84000)
        },
        'sirach': {
            'patterns': [r'Sirach 1:1', r'The Wisdom ofJesus theSonofSirach'],
            'range': (78533, 82324)
        },
        'baruch': {
            'patterns': [r'Baruch 1:1', r'These arethewords ofthebook'],
            'range': (97186, 98500)
        },
        '1maccabees': {
            'patterns': [r'1Maccabees 1:1', r'After Alexander theMacedonian'],
            'range': (54674, 58171)
        },
        '2maccabees': {
            'patterns': [r'2Maccabees 1:1', r'Brothers living inJerusalem'],
            'range': (58172, 65000)
        },
        'susanna': {
            'patterns': [r'THE HISTORY OFSUSANNA', r'noon, Susanna went into'],
            'range': (105500, 107000)
        }
    }
    
    output_dir = "../html/en/"
    os.makedirs(output_dir, exist_ok=True)
    
    for book_key, book_info in books_to_extract.items():
        print(f"\nExtracting {book_key}...")
        
        # Try pattern-based extraction first
        book_text = extract_book_by_pattern(full_text, book_info['patterns'], book_key)
        
        # If pattern fails, try line range
        if not book_text:
            print(f"Pattern failed, trying line range {book_info['range']}")
            start_line, end_line = book_info['range']
            book_text = extract_book_by_lines(lines, start_line, end_line, book_key)
        
        if book_text:
            # Apply comprehensive text spacing fixes
            cleaned_text = fix_text_spacing(book_text)
            
            if cleaned_text:
                html_content = format_as_html(book_key.replace('maccabees', ' Maccabees').title(), cleaned_text)
                output_file = os.path.join(output_dir, f"{book_key}.htm")
                
                with open(output_file, 'w', encoding='utf-8') as f:
                    f.write(html_content)
                
                print(f"Created {output_file} with improved spacing")
            else:
                print(f"No content after cleaning for {book_key}")
        else:
            print(f"Could not extract {book_key}")

if __name__ == "__main__":
    main()